(ns egd-wallist.core-test
  (:require [egd-wallist.core :as core]
            #?(:clj [clojure.test :refer [deftest is testing]]
               :cljs [cljs.test :refer [deftest is testing] :include-macros true])))

(deftest test-example-wallist-0
  (is (= {:tags
          {:CL "A",
           :EV "Tournament name",
           :PC ",Location name",
           :DT "2021-09-18,2021-09-18",
           :KM "7.5",
           :TM "82",
           :CM "Standard byo-yomi"},
          :comments
          " Generated by OpenGotha 3.52\n\n Pl Name                            Rk Co Club  NBW  SOSSOSOS",
          :players
          [{:last-name "145294584077877249",
            :game-results
            [{:type :result,
              :opponent-place "2",
              :result "?",
              :colour "b",
              :handicap "0"}],
            :place "1",
            :rank "3D",
            :type :player,
            :first-name "x",
            :club "XXXX",
            :scores ["0" "0" "0" "0"],
            :country "AB"}
           {:last-name "477895596141707264",
            :game-results
            [{:type :result,
              :opponent-place "1",
              :result "?",
              :colour "w",
              :handicap "0"}],
            :place "2",
            :rank "3K",
            :type :player,
            :first-name "x",
            :club "XXXX",
            :scores ["0" "0" "0" "0"],
            :country "AB"}]}
         (core/read-wallist "; CL[A]
; EV[Tournament name]
; PC[,Location name]
; DT[2021-09-18,2021-09-18]
; KM[7.5]
; TM[82]
; CM[Standard byo-yomi]
; Generated by OpenGotha 3.52
;
; Pl Name                            Rk Co Club  NBW  SOSSOSOS
   1 145294584077877249 x            3D AB XXXX    0    0    0 0    2?/b0
     477895596141707264 x            3K AB XXXX    0    0    0 0    1?/w0
"))))
